# All
- hosts: cloud.*
  vars:
    image: 'cedricprigent/air-quality-hpo:0.0.1'
    container_name: 'lr_hpo'
    save_dir: '/home/cprigent/runs/aqf/hpo/'

  prepare:
    - name: Checking Docker Installation
      command: docker --version
      register: docker_valid
      ignore_errors: yes
    - name: Installing docker
      shell: '/grid5000/code/bin/g5k-setup-docker'
      when: docker_valid.failed
    - name: Pull docker image
      shell: 'docker pull {{ image }}'
  
  launch:
    - name: Running docker image
      shell: 'docker run --rm --privileged --network=host --volume /tmp/log:/app/log --name {{ container_name }} {{ image }}'
  
  finalize:
    - name: Retreiving log files
      shell: "cp -r /tmp/log {{ save_dir }} "